version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "minecraft-api"
s3_bucket = "my-bucket-name"
s3_prefix = "minecraft-api"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MinecraftServerInstanceId=\"i-1234abc5678d9012e\",UserLoginTableName=\"ParameterValue=MyKey\""
