version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "minecraft-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cufltg62ifa2"
s3_prefix = "minecraft-api"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MinecraftServerInstanceId=\"i-0818abb5386b0082a\",UserLoginTableName=\"ParameterValue=MyKey\""
